/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 20 22:59:09 GMT 2018
 */

package android.support.v7.cardview;

import org.junit.Test;
import static org.junit.Assert.*;
import android.support.v7.cardview.R;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class R_ESTest extends R_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      R.style r_style0 = new R.style();
      assertEquals(2131755183, R.style.CardView_Dark);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      R.styleable r_styleable0 = new R.styleable();
      assertEquals(7, R.styleable.CardView_cardUseCompatPadding);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      R r0 = new R();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      R.dimen r_dimen0 = new R.dimen();
      assertEquals(2131165260, R.dimen.cardview_compat_inset_shadow);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      R.attr r_attr0 = new R.attr();
      assertEquals(2130968653, R.attr.cardElevation);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      R.color r_color0 = new R.color();
      assertEquals(2131099687, R.color.cardview_light_background);
  }
}
