/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 20 22:47:45 GMT 2018
 */

package android.support.constraint;

import org.junit.Test;
import static org.junit.Assert.*;
import android.support.constraint.R;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class R_ESTest extends R_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      R.id r_id0 = new R.id();
      assertEquals(2131361971, R.id.spread);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      R.styleable r_styleable0 = new R.styleable();
      assertEquals(60, R.styleable.ConstraintSet_layout_goneMarginLeft);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      R.attr r_attr0 = new R.attr();
      assertEquals(2130968787, R.attr.layout_constraintHorizontal_bias);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      R r0 = new R();
  }
}
