/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 20 22:48:12 GMT 2018
 */

package com.github.ghcli;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.ghcli.BuildConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BuildConfig_ESTest extends BuildConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BuildConfig buildConfig0 = new BuildConfig();
      assertEquals(1, BuildConfig.VERSION_CODE);
  }
}
