/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 20 22:55:28 GMT 2018
 */

package com.github.ghcli;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.ghcli.R;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class R_ESTest extends R_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      R.anim r_anim0 = new R.anim();
      assertEquals(2130771975, R.anim.abc_slide_in_top);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      R.attr r_attr0 = new R.attr();
      assertEquals(2130968771, R.attr.layout_collapseMode);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      R.font r_font0 = new R.font();
      assertEquals(2131296256, R.font.montserrat);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      R.mipmap r_mipmap0 = new R.mipmap();
      assertEquals(2131623936, R.mipmap.ic_launcher);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      R.layout r_layout0 = new R.layout();
      assertEquals(2131492888, R.layout.abc_search_dropdown_item_icons_2line);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      R.styleable r_styleable0 = new R.styleable();
      assertEquals(4, R.styleable.TabLayout_tabIndicatorHeight);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      R.animator r_animator0 = new R.animator();
      assertEquals(2130837504, R.animator.design_appbar_state_list_animator);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      R.color r_color0 = new R.color();
      assertEquals(2131099715, R.color.material_blue_grey_950);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      R.id r_id0 = new R.id();
      assertEquals(2131361808, R.id.action_divider);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      R r0 = new R();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      R.dimen r_dimen0 = new R.dimen();
      assertEquals(2131165261, R.dimen.cardview_default_elevation);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      R.menu r_menu0 = new R.menu();
      assertEquals(2131558401, R.menu.menu_ghcli);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      R.bool r_bool0 = new R.bool();
      assertEquals(2131034116, R.bool.abc_config_showMenuShortcutsWhenKeyboardPresent);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      R.integer r_integer0 = new R.integer();
      assertEquals(2131427331, R.integer.bottom_sheet_slide_duration);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      R.style r_style0 = new R.style();
      assertEquals(2131755362, R.style.Widget_AppCompat_Light_ActionButton_Overflow);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      R.array r_array0 = new R.array();
      assertEquals(2130903041, R.array.com_google_android_gms_fonts_certs_dev);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      R.string r_string0 = new R.string();
      assertEquals(2131689493, R.string.abc_font_family_title_material);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      R.drawable r_drawable0 = new R.drawable();
      assertEquals(2131230752, R.drawable.abc_ic_menu_overflow_material);
  }
}
