/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 20 22:57:40 GMT 2018
 */

package com.github.ghcli.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.ghcli.service.ServiceGenerator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ServiceGenerator_ESTest extends ServiceGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        ServiceGenerator.createService((Class<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("retrofit2.Utils", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ServiceGenerator serviceGenerator0 = new ServiceGenerator();
  }
}
