/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Feb 20 22:57:40 GMT 2018
 */

package com.github.ghcli.service;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ServiceGenerator_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.github.ghcli.service.ServiceGenerator"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.timezone", "America/Fortaleza"); 
    java.lang.System.setProperty("sun.jnu.encoding", "UTF-8"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ServiceGenerator_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.gson.internal.bind.TimeTypeAdapter$1",
      "okhttp3.RequestBody$1",
      "okio.Timeout$1",
      "okio.Options",
      "com.google.gson.internal.bind.JsonTreeWriter",
      "com.google.gson.JsonDeserializationContext",
      "okhttp3.internal.platform.AndroidPlatform$AndroidCertificateChainCleaner",
      "okhttp3.OkHttpClient$1",
      "okio.BufferedSink",
      "com.google.gson.internal.bind.TimeTypeAdapter",
      "okhttp3.CookieJar",
      "okhttp3.Request",
      "okio.SegmentedByteString",
      "okio.BufferedSource",
      "com.google.gson.LongSerializationPolicy",
      "com.google.gson.internal.bind.TypeAdapters$35$1",
      "com.google.gson.internal.Excluder",
      "okhttp3.RequestBody$2",
      "okhttp3.RequestBody$3",
      "okhttp3.Handshake",
      "okhttp3.Call$Factory",
      "com.google.gson.annotations.Until",
      "com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter",
      "com.google.gson.stream.JsonReader$1",
      "com.google.gson.internal.$Gson$Types",
      "okio.Source",
      "okhttp3.CipherSuite$1",
      "okio.Sink",
      "okhttp3.CookieJar$1",
      "retrofit2.Utils",
      "okhttp3.EventListener$1",
      "com.google.gson.Gson$FutureTypeAdapter",
      "okhttp3.EventListener",
      "okhttp3.EventListener$2",
      "okhttp3.Response$Builder",
      "com.google.gson.internal.bind.TreeTypeAdapter",
      "okhttp3.Response",
      "okhttp3.Call",
      "okhttp3.Authenticator$1",
      "com.google.gson.stream.JsonWriter",
      "com.google.gson.internal.bind.ArrayTypeAdapter$1",
      "com.google.gson.internal.$Gson$Preconditions",
      "okhttp3.internal.connection.RealConnection$1",
      "retrofit2.Platform$Android",
      "okhttp3.OkHttpClient",
      "okhttp3.ConnectionSpec$Builder",
      "com.google.gson.internal.ObjectConstructor",
      "com.google.gson.JsonNull",
      "okhttp3.internal.platform.JdkWithJettyBootPlatform",
      "okio.Buffer$2",
      "okio.Buffer$1",
      "com.google.gson.LongSerializationPolicy$1",
      "com.google.gson.LongSerializationPolicy$2",
      "com.google.gson.JsonObject",
      "com.google.gson.internal.bind.JsonTreeReader$1",
      "okhttp3.Authenticator",
      "okhttp3.CertificatePinner",
      "com.google.gson.Gson$2",
      "com.google.gson.Gson$3",
      "com.google.gson.internal.bind.ObjectTypeAdapter",
      "com.google.gson.Gson$4",
      "okhttp3.internal.cache.CacheRequest",
      "com.google.gson.Gson$5",
      "com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter",
      "com.google.gson.Gson$1",
      "okhttp3.CipherSuite",
      "com.google.gson.Gson",
      "okhttp3.internal.Util",
      "com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory",
      "retrofit2.Converter",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory",
      "okhttp3.ConnectionPool$1",
      "okhttp3.WebSocket",
      "okhttp3.internal.tls.BasicTrustRootIndex",
      "retrofit2.Retrofit",
      "okhttp3.CertificatePinner$Builder",
      "retrofit2.DefaultCallAdapterFactory",
      "com.google.gson.internal.Excluder$1",
      "com.google.gson.internal.bind.TypeAdapters$2",
      "com.google.gson.internal.bind.TypeAdapters$1",
      "com.google.gson.internal.bind.JsonTreeWriter$1",
      "okhttp3.EventListener$Factory",
      "retrofit2.BuiltInConverters",
      "okhttp3.HttpUrl$Builder",
      "okhttp3.internal.http.HttpCodec",
      "com.google.gson.JsonIOException",
      "com.google.gson.internal.bind.TypeAdapters$8",
      "com.google.gson.internal.bind.TypeAdapters$7",
      "okhttp3.internal.http2.Http2Connection$Listener$1",
      "com.google.gson.internal.bind.TypeAdapters",
      "com.google.gson.internal.bind.TypeAdapters$9",
      "okhttp3.OkHttpClient$Builder",
      "com.google.gson.internal.bind.TypeAdapters$4",
      "com.google.gson.internal.bind.TypeAdapters$3",
      "okhttp3.internal.platform.Platform",
      "com.google.gson.internal.bind.TypeAdapters$6",
      "com.google.gson.internal.bind.TypeAdapters$5",
      "okhttp3.internal.connection.RouteDatabase",
      "okhttp3.RequestBody",
      "com.google.gson.FieldNamingPolicy",
      "com.google.gson.internal.bind.CollectionTypeAdapterFactory",
      "retrofit2.converter.gson.GsonConverterFactory",
      "com.google.gson.JsonPrimitive",
      "okio.Buffer",
      "okhttp3.Dns$1",
      "okhttp3.internal.Util$1",
      "com.google.gson.JsonSyntaxException",
      "retrofit2.Platform$Java8",
      "okhttp3.internal.Util$2",
      "okhttp3.Dns",
      "okhttp3.internal.platform.Jdk9Platform",
      "com.google.gson.reflect.TypeToken",
      "okhttp3.Cache",
      "retrofit2.CallAdapter$Factory",
      "com.google.gson.internal.bind.TypeAdapters$23",
      "com.google.gson.internal.bind.TypeAdapters$24",
      "com.google.gson.internal.bind.TypeAdapters$25",
      "com.google.gson.internal.bind.TypeAdapters$26",
      "com.google.gson.internal.bind.TypeAdapters$20",
      "com.google.gson.TypeAdapter",
      "com.google.gson.internal.bind.TypeAdapters$21",
      "okhttp3.Dispatcher",
      "com.google.gson.internal.bind.TypeAdapters$22",
      "okhttp3.Address",
      "okhttp3.Route",
      "com.google.gson.internal.bind.TypeAdapters$27",
      "com.google.gson.FieldNamingStrategy",
      "com.google.gson.internal.bind.TypeAdapters$28",
      "com.google.gson.internal.bind.TypeAdapters$29",
      "com.google.gson.internal.bind.SqlDateTypeAdapter",
      "com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper",
      "okhttp3.Headers$Builder",
      "com.google.gson.ExclusionStrategy",
      "okhttp3.ResponseBody",
      "retrofit2.Platform",
      "okhttp3.internal.tls.CertificateChainCleaner",
      "com.google.gson.internal.bind.TypeAdapters$34",
      "com.google.gson.internal.bind.TypeAdapters$35",
      "com.google.gson.internal.bind.TypeAdapters$30",
      "com.google.gson.internal.bind.TypeAdapters$32",
      "okhttp3.Connection",
      "com.google.gson.internal.bind.TypeAdapters$33",
      "com.google.gson.JsonArray",
      "okhttp3.internal.ws.RealWebSocket$Streams",
      "com.google.gson.TypeAdapterFactory",
      "com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter",
      "okhttp3.internal.cache.InternalCache",
      "okhttp3.internal.tls.BasicCertificateChainCleaner",
      "okhttp3.WebSocketListener",
      "com.google.gson.stream.JsonReader",
      "com.google.gson.internal.bind.MapTypeAdapterFactory",
      "okhttp3.internal.Internal",
      "com.google.gson.internal.bind.TypeAdapters$12",
      "com.google.gson.internal.bind.TypeAdapters$13",
      "okhttp3.ResponseBody$1",
      "com.google.gson.internal.bind.TypeAdapters$14",
      "com.google.gson.internal.bind.TypeAdapters$15",
      "com.google.gson.internal.bind.TypeAdapters$10",
      "com.google.gson.internal.bind.TypeAdapters$11",
      "com.google.gson.stream.MalformedJsonException",
      "com.google.gson.internal.bind.ArrayTypeAdapter",
      "com.google.gson.internal.bind.TypeAdapters$16",
      "com.google.gson.internal.bind.TypeAdapters$17",
      "okhttp3.internal.connection.RouteException",
      "com.google.gson.internal.bind.TypeAdapters$18",
      "com.google.gson.internal.bind.TypeAdapters$19",
      "com.google.gson.internal.bind.DateTypeAdapter$1",
      "retrofit2.CallAdapter",
      "okhttp3.ConnectionPool",
      "okhttp3.HttpUrl$Builder$ParseResult",
      "okhttp3.WebSocket$Factory",
      "com.google.gson.TypeAdapter$1",
      "com.google.gson.internal.bind.DateTypeAdapter",
      "com.google.gson.internal.bind.TypeAdapters$26$1",
      "okio.Timeout",
      "okhttp3.internal.connection.StreamAllocation",
      "okhttp3.ConnectionSpec",
      "okio.Segment",
      "retrofit2.ExecutorCallAdapterFactory",
      "okhttp3.internal.platform.AndroidPlatform",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$BoundField",
      "okhttp3.internal.http2.Http2Connection$Listener",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1",
      "com.google.gson.internal.bind.JsonTreeReader",
      "com.google.gson.internal.bind.SqlDateTypeAdapter$1",
      "okhttp3.Protocol",
      "okhttp3.HttpUrl",
      "okhttp3.internal.connection.RealConnection",
      "com.google.gson.internal.LazilyParsedNumber",
      "com.google.gson.internal.bind.ObjectTypeAdapter$1",
      "com.google.gson.JsonParseException",
      "okhttp3.ResponseBody$BomAwareReader",
      "com.google.gson.internal.ConstructorConstructor",
      "com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter",
      "com.google.gson.JsonElement",
      "okio.ByteString",
      "com.google.gson.JsonSerializationContext",
      "retrofit2.Converter$Factory",
      "okio.Util",
      "okhttp3.internal.tls.OkHostnameVerifier",
      "okhttp3.internal.tls.TrustRootIndex",
      "retrofit2.Retrofit$Builder",
      "com.google.gson.FieldNamingPolicy$4",
      "com.google.gson.FieldNamingPolicy$3",
      "com.google.gson.annotations.Since",
      "com.google.gson.FieldNamingPolicy$5",
      "com.google.gson.internal.JsonReaderInternalAccess",
      "com.github.ghcli.service.ServiceGenerator",
      "okhttp3.TlsVersion",
      "com.google.gson.FieldNamingPolicy$2",
      "com.google.gson.FieldNamingPolicy$1"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ServiceGenerator_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "okhttp3.Protocol",
      "okio.Buffer",
      "okio.Util",
      "okio.ByteString",
      "okhttp3.internal.Util",
      "okhttp3.CipherSuite",
      "okhttp3.TlsVersion",
      "okhttp3.ConnectionSpec",
      "okhttp3.internal.Internal",
      "okhttp3.OkHttpClient",
      "okhttp3.EventListener",
      "okhttp3.CookieJar",
      "okhttp3.internal.tls.OkHostnameVerifier",
      "okhttp3.CertificatePinner",
      "okhttp3.Authenticator",
      "okhttp3.ConnectionPool",
      "okhttp3.Dns",
      "retrofit2.Platform",
      "retrofit2.Utils",
      "okhttp3.HttpUrl",
      "okhttp3.HttpUrl$Builder$ParseResult",
      "com.google.gson.internal.$Gson$Types",
      "com.google.gson.Gson",
      "com.google.gson.internal.Excluder",
      "com.google.gson.FieldNamingPolicy$1",
      "com.google.gson.FieldNamingPolicy$2",
      "com.google.gson.FieldNamingPolicy$3",
      "com.google.gson.FieldNamingPolicy$4",
      "com.google.gson.FieldNamingPolicy$5",
      "com.google.gson.FieldNamingPolicy",
      "com.google.gson.LongSerializationPolicy$1",
      "com.google.gson.LongSerializationPolicy$2",
      "com.google.gson.LongSerializationPolicy",
      "com.google.gson.internal.bind.TypeAdapters$27",
      "com.google.gson.internal.bind.TypeAdapters",
      "com.google.gson.internal.bind.ObjectTypeAdapter",
      "com.google.gson.internal.bind.DateTypeAdapter",
      "com.google.gson.internal.bind.TimeTypeAdapter",
      "com.google.gson.internal.bind.SqlDateTypeAdapter",
      "com.google.gson.internal.bind.ArrayTypeAdapter",
      "com.github.ghcli.service.ServiceGenerator",
      "okhttp3.internal.platform.AndroidPlatform",
      "okhttp3.internal.platform.Platform",
      "okhttp3.internal.tls.BasicCertificateChainCleaner",
      "retrofit2.DefaultCallAdapterFactory"
    );
  }
}
