/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 20 22:48:30 GMT 2018
 */

package butterknife;

import org.junit.Test;
import static org.junit.Assert.*;
import butterknife.R;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class R_ESTest extends R_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      R r0 = new R();
  }
}
