/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 20 22:50:29 GMT 2018
 */

package android.support.design;

import org.junit.Test;
import static org.junit.Assert.*;
import android.support.design.R;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class R_ESTest extends R_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      R.integer r_integer0 = new R.integer();
      assertEquals(2131427331, R.integer.bottom_sheet_slide_duration);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      R.bool r_bool0 = new R.bool();
      assertEquals(2131034114, R.bool.abc_config_actionMenuItemAllCaps);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      R.string r_string0 = new R.string();
      assertEquals(2131689520, R.string.password_toggle_content_description);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      R.id r_id0 = new R.id();
      assertEquals(2131361874, R.id.forever);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      R.animator r_animator0 = new R.animator();
      assertEquals(2130837504, R.animator.design_appbar_state_list_animator);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      R.style r_style0 = new R.style();
      assertEquals(2131755314, R.style.Theme_Design_Light);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      R.styleable r_styleable0 = new R.styleable();
      assertEquals(0, R.styleable.TabItem_android_icon);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      R r0 = new R();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      R.drawable r_drawable0 = new R.drawable();
      assertEquals(2131230828, R.drawable.notification_bg_normal_pressed);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      R.anim r_anim0 = new R.anim();
      assertEquals(2130771973, R.anim.abc_shrink_fade_out_from_bottom);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      R.attr r_attr0 = new R.attr();
      assertEquals(2130968619, R.attr.autoCompleteTextViewStyle);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      R.dimen r_dimen0 = new R.dimen();
      assertEquals(2131165248, R.dimen.abc_text_size_headline_material);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      R.layout r_layout0 = new R.layout();
      assertEquals(2131492899, R.layout.design_layout_tab_icon);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      R.color r_color0 = new R.color();
      assertEquals(2131099715, R.color.material_blue_grey_950);
  }
}
